BaseUrl= "https://vmarcospblog.netlify.com/"
LanguageCode= "pt-BR"
Title= "Marcos Vinicius"
paginate = 5
DisqusShortname = "vmarcosp"
Copyright = "Copyright - 2017"
canonifyurls = true
theme = "casper"
publishDir = "public"

[params]
  description = "Full-Stack Web Developer "
  metadescription = "Blog de um maker bug"

  author = "Marcos Vinicius de Oliveira"
  authorlocation = "Blumenau, Brasil"
  authorwebsite = "https://vmarcospblog.netlify.com/"
  authorbio= "A Developer"

  googleAnalyticsUserID = "UA-79101-12"
  RSSLink = "http://feeds.feedburner.com/..."

  cover = "images/bg-blur.jpeg"
  logo = "images/logo.svg"
  footerLogo = "images/me.png"
  customCss = ["css/nav-custom.css"]

  githubName = "vmarcosp"
  # twitterName = "vmarcosp"
  linkedinName = "marcos-vinicius-oliveira-20baa3129"

  hideHUGOSupport = false

  hjsStyle = "default"

  [params.social]
    # twitter = "your_twitter"
