BaseUrl= "https://vmarcospblog.netlify.com/"
LanguageCode= "pt-br"
Title= "Marcos Vinicius"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "Copyright - 2017"
canonifyurls = true
theme = "casper"
publishDir = "public"

[params]
  description = "Full-Stack Web Developer "
  metadescription = "Blog de um maker bug"

  author = "Valère JEANTET"
  authorlocation = "Paris, France"
  authorwebsite = "http://vjeantet.fr"
  authorbio= "my bio"

  googleAnalyticsUserID = "UA-79101-12"
  RSSLink = "http://feeds.feedburner.com/..."

  cover = "images/background.jpg"
  logo = "images/logo.svg"
  customCss = ["css/nav-custom.css"]

  githubName = "vmarcosp"
  twitterName = "vmarcosp"
  linkedinName = "marcos-vinicius-oliveira-20baa3129"

  hideHUGOSupport = false

  hjsStyle = "default"

  [params.social]
    twitter = "your_twitter"
