BaseUrl= "/"
LanguageCode= "pt-BR"
Title= "Marcos Vinicius"
paginate = 5
DisqusShortname = "vmarcosp-com-br"
Copyright = "2017"
canonifyurls = true
theme = "casper"
publishDir = "public"

[params]
  description = "Full-Stack Web Developer "
  metadescription = "Blog de um maker bug"

  author = "Marcos Vinicius de Oliveira"
  authorlocation = "Blumenau, Brasil"
  authorwebsite = "http://vmarcosp.com.br/"
  authorbio= "A Developer"

  googleAnalyticsUserID = "UA-107728478-1"
  # RSSLink = "http://feeds.feedburner.com/..."

  cover = "images/bg-blur.jpeg"
  logo = "images/logo.svg"
  footerLogo = "images/me.png"
  customCss = ["css/nav-custom.css","css/icons-custom.css","css/footer-custom.css","css/style-custom.css"]
  customJs = ["js/index.js"]
  githubName = "vmarcosp"
  linkedinName = "marcos-vinicius-oliveira-20baa3129"
  codepenName = "vmarcosp"
  comments = true
  # hideHUGOSupport = false

  hjsStyle = "default"
  # twitterName = "vmarcosp"

  [params.social]
    # twitter = "your_twitter"
